### ISSUE TITLE
Any field have default value, field must be not mandatory.

### ISSUE THREAD

**Issue by nareshelequin** [jknaresh/django_generic_api#34]
If model have field and it consists of default value, should not be an mandatory value.

in case,  User input's to field as null or empty, assign default value.

model field:

inserted_timestamp = models.DateTimeField(default=timezone.now, null=False)

Response as error: 
{
    "error": "{'error': \"Field required. ('inserted_timestamp',)\", 'code': 'DGA-S006'}",
    "code": "DGA-V005"
}

**Comment by ShrijanL** [comment]
understood the bug,
if null = false and default value is provided, take the default value.
if null = false and no default value, raises error.
until now, if null is false, field is a required value
from now, 
         if null is false, default value is not provided, field is required.
         if null is false, default value is provided, field is not required.
         if null is true, field is not required.
